services:
  server:
    build:
      context: .
    ports:
      - 3000:3000
      - 5555:5555
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app    
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-courses-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-courses-data: